In [1]:
import numpy as np

In [3]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
rand_array=np.random.randint(0,10,50)
rand_array

array([0, 4, 6, 0, 3, 0, 0, 1, 6, 3, 3, 4, 3, 6, 3, 8, 7, 5, 9, 5, 5, 5,
       7, 8, 6, 0, 6, 6, 2, 8, 7, 0, 7, 8, 0, 6, 5, 4, 3, 6, 3, 3, 4, 2,
       3, 0, 5, 6, 3, 8])

In [5]:
rand_array.max()

9

In [6]:
rand_array.argmax()

18

In [2]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
a=np.random.rand(2,3)
a

array([[0.24022255, 0.18387628, 0.97166339],
       [0.50649746, 0.61859052, 0.49506018]])

In [8]:
a.T

array([[0.24022255, 0.50649746],
       [0.18387628, 0.61859052],
       [0.97166339, 0.49506018]])

In [9]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
sample_array[0]

10

In [11]:
sample_array[2:5]

array([12, 13, 14])

In [12]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [13]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [16]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [17]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])