# Machine Learning Librarys

## Numpy:Package for Multidimentional Array

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(4,18)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [5]:
np.arange(1,40,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36])

In [6]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.ones((2,3),int)

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [26]:
np.random.rand(2,3)

array([[0.08988212, 0.70893714, 0.36258659],
       [0.74066572, 0.53213982, 0.88273566]])

In [27]:
np.random.rand(2,3)

array([[0.21062715, 0.94251925, 0.3472629 ],
       [0.19902802, 0.76477196, 0.73035677]])

In [28]:
arr=np.random.randn(2,3)
arr

array([[ 1.96228667,  0.60089484, -0.00548387],
       [-0.18513523, -0.5268479 , -1.05466876]])

In [29]:
np.random.randint(2,100)

35

In [30]:
np.random.randint(2,100)

71

In [31]:
np.random.randint(2,100)

2

In [32]:
np.random.randint(2,100)

82

In [33]:
np.random.randint(20,56,100)

array([36, 54, 43, 33, 35, 46, 32, 44, 20, 36, 27, 25, 52, 40, 30, 45, 40,
       39, 32, 31, 45, 39, 43, 34, 42, 29, 39, 43, 35, 50, 50, 44, 41, 43,
       42, 39, 45, 32, 40, 21, 51, 29, 35, 45, 29, 30, 43, 38, 33, 34, 52,
       36, 47, 25, 25, 52, 48, 21, 40, 30, 20, 36, 52, 47, 25, 33, 26, 50,
       50, 37, 23, 51, 44, 22, 24, 30, 41, 31, 21, 45, 24, 54, 36, 26, 41,
       28, 40, 47, 20, 24, 26, 51, 55, 53, 26, 32, 27, 34, 20, 51])

In [38]:
sample_array=np.arange(12)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
rand_array=np.random.randint(0,10,50)
rand_array

array([0, 0, 8, 3, 9, 7, 6, 1, 3, 0, 8, 0, 9, 0, 7, 1, 8, 9, 7, 6, 9, 1,
       2, 4, 6, 4, 2, 6, 9, 0, 6, 4, 1, 2, 7, 3, 4, 9, 8, 8, 6, 1, 2, 5,
       9, 0, 2, 8, 6, 9])

In [39]:
sample_array.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])